### ISSUE TITLE
test

### ISSUE THREAD

**Issue by chestozo** [chestozo/knol#3]

**Comment by chestozo** [comment]
> когда важен контекст, и от контекста зависит перевод

делаешь новый ключ
и вообще, у нас железное правило - ключи не меняем а добавляем новые

**Comment by i2r** [comment]
> когда важен контекст, и от контекста зависит перевод

Скопировал текст и откомментил.

**Comment by i2r** [comment]
> когда важен контекст, и от контекста зависит перевод

Пожалуйста: ещё раз откомментил.

**Comment by i2r** [comment]
> когда важен контекст, и от контекста зависит перевод

Ещё газик.
